import Header from '@/components/Header'
import './globals.css'
import Provider from '../theming/Provider';
import Navbar from '@/components/navbar/Navbar';

export const metadata = {
  title: 'IMDB Clone | Movies, Series, TV, Sports',
  description: 'Generated by Skullomanic',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header />
          <Navbar />
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
